# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QPushButton, QApplication, QWidget, QPushButton, QMessageBox
from methods import logger, downloader


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 159)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(776, 159))
        MainWindow.setMaximumSize(QtCore.QSize(776, 159))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(80, 10, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_url.setFont(font)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.hely_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hely_btn.setGeometry(QtCore.QRect(680, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hely_btn.setFont(font)
        self.hely_btn.setObjectName("hely_btn")
        self.letoltes_btn = QtWidgets.QPushButton(self.centralwidget)
        self.letoltes_btn.setGeometry(QtCore.QRect(10, 50, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.letoltes_btn.setFont(font)
        self.letoltes_btn.setObjectName("letoltes_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.hely_btn.pressed.connect(self.mentes)
        self.letoltes_btn.pressed.connect(self.letoltes)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Projekt feladat"))
        self.label.setText(_translate("MainWindow", "URL:"))
        self.hely_btn.setText(_translate("MainWindow", "Hely"))
        self.letoltes_btn.setText(_translate("MainWindow", "Letöltés"))
    
    def mentes(self):
        self.hely_btn = QFileDialog.getSaveFileName()
        logger(self.hely_btn)
        if self.hely_btn[0] == '':
            popup = QMessageBox()
            popup.setWindowTitle("Hiba")
            popup.setText("Nem adtál meg mentési helyet!")
            popup.exec()

    def letoltes(self):
        if self.lineEdit_url.text() == '':
            popup = QMessageBox()
            popup.setWindowTitle("Hiba")
            popup.setText("Nem adtál meg mentési URL-t!")
            popup.exec()
            return

        downloader(self.lineEdit_url.text(), self.hely_btn[0])
        popup = QMessageBox()
        popup.setWindowTitle("Infó")
        popup.setText("Letöltés kész!")
        popup.exec()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
